name: Update Data And Publish Site
on:
  push:
    branches:
      - "main"
  # GitHub Actions use UTC time, so 21:00 means 5:00 UTC +8 Timezone
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-cache
      - run: npm run crawl
      - run: npm run build
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: f335dee5609bac21c6bdf7b9a0a68b9d
          projectName: ma7
          directory: out
