name: Update Data And Publish Site
on:
  push:
    branches:
      - "main"
  # GitHub Actions use UTC time, so 21:00 means 5:00 UTC +8 Timezone
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-cache
      - name: Fetch data
        run: npm run crawl
      - name: Build site
        run: npm run build
      - name: Deploy to Cloudflare Pages
        run: |
          export CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          export CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          npx wrangler pages deploy out --project-name=ma7 --branch=main
